Change error name to reflect the type
MasterKale/SimpleWebAuthn pull request #191
Opened 2022-04-03 09:11 UTC by felixmosh

fixes #190

2022-04-04 03:29 UTC, MasterKale commented
Hmm, I don't like the idea of calling an error "WebAuthnError" and then allowing for its name to be overridden so `error.name` would never be `"WebAuthnError"`. The better way to do this is probably to throw basic `Error`'s instead and set the name to the original WebAuthn error so that RPs like you can continue to rely on `error.name` for detection. Then just drop `"WebAuthnError"` completely so what the functionality really becomes is an overriding of the description of the error.

2022-04-11 05:23 UTC, MasterKale commented
I experimented with some potential solutions tonight and after hitting a bunch of dead ends I do think your proposed solution is the only way forward. I'm going to request a fix, and once that's done this should be good to merge.

2022-04-11 05:26 UTC, MasterKale requested changes

2022-04-11 05:26 UTC, MasterKale commented on packages/browser/src/helpers/identifyAuthenticationError.ts
> +        'Authentication ceremony was sent an abort signal (AbortError)',
Since the error name will now convey this, can you please remove from all error messages the error name in the parenthesis? It's being made redundant by these changes.

e.g. drop "(AbortError)" from "Authentication ceremony was sent an abort signal (AbortError)"

2022-04-11 05:26 UTC, MasterKale commented on packages/browser/src/helpers/identifyAuthenticationError.ts
> +        'AbortError',
Can you also update tests to ensure that the `name` property on all thrown errors is the appropriate value? That seems to me to be the most important thing to assert in all this, that SimpleWebAuthn doesn't nuke the actual error name again and break existing code that relies on it.

2022-04-11 07:57 UTC, felixmosh commented on packages/browser/src/helpers/identifyAuthenticationError.ts
> +        'Authentication ceremony was sent an abort signal (AbortError)',
I've updated the messages, but for some reason I can't run tests locally, fails on typescript :|

2022-04-11 16:17 UTC, MasterKale commented on packages/browser/src/helpers/identifyAuthenticationError.ts
> +        'Authentication ceremony was sent an abort signal (AbortError)',
I'll bet I know what you're running into. The tests for this functionality are in a sorry state, I was fighting them myself just last night. The issue was I assumed `NotAllowedError`/`SecurityError`/etc... were actual subclasses of `Error` that should exist on `global`. Instead they're simply instances of `Error` with custom `name` properties (because of course they are 🤦) and I wasted a bunch of time trying to mock them out.

The solution will probably be to update the tests to check `name` instead of the type of the error, and then rip out all of the custom error subclasses I defined for the tests. I'll take some time tonight to do this and get it on master so that `test` and `test:watch` resume working as expected. Afterwards you should be able to rebase on them and get tests running locally.

Apologies for the inconvenience 😅

2022-04-12 03:58 UTC, MasterKale commented on packages/browser/src/helpers/identifyAuthenticationError.ts
> +        'Authentication ceremony was sent an abort signal (AbortError)',
@felixmosh I just merged #194 that should fix the local browser testing issues. Can you rebase off of **master** and try again?

2022-04-12 06:03 UTC, felixmosh commented
I've updated tests, thank you

2022-04-13 15:23 UTC, MasterKale approved these changes

2022-04-13 15:27 UTC, merged

2022-04-13 15:27 UTC, MasterKale commented
@felixmosh Thank you for your contribution! This is a great improvement to the error detection logic 🚀