Add a better Device Public Key support
MasterKale/SimpleWebAuthn pull request #267
Opened 2022-09-10 06:04 UTC by agektmr

This pull request adds a better device public key support.
You may start reviewing this, but I will keep this as draft until the spec is closer to final.

2022-09-20 04:07 UTC, MasterKale requested changes
For some reason this diff includes **package-lock.json** files despite their being an entry in **.gitignore** to leave them out. Libraries intentionally omit these files so that consuming libraries are free to upgrade to the latest version of libraries as per the individual libraries' **package.json** files.

Can you please remove all package-lock.json files in **packages/** from this diff?

2022-09-20 04:19 UTC, MasterKale commented on packages/typescript-types/src/index.ts
> +  devicePubKey?: AuthenticationExtensionsDevicePublicKeyOutputsJSON
**@simplewebauthn/browser**'s `startRegistration()` and `startAuthentication()` are going to need corresponding updates to encode `devicePubKey` if it's present. Right now I think the library naively calls `credential.getClientExtensionResults()` which, until `devicePubKey`, returned JSON-serializable values that required no additional processing.

2022-09-20 04:19 UTC, MasterKale commented on packages/typescript-types/src/index.ts
> +  attestation: string;
This should be updated to type `AttestationConveyancePreference`, importable with the other entries from `"./dom"`.

2022-09-20 04:19 UTC, MasterKale commented on packages/typescript-types/src/index.ts
> +  attestationFormats: string[];
This can be refined to `AttestationFormat[]`, but unfortunately `AttestationFormat` containing these various values currently resides in **packages/server/src/helpers/decodeAttestationObject.ts**. I suggest we move `AttestationFormat` out of there and into **@simplewebauthn/typescript-types** so that we can share it for use here too.

2022-09-20 04:19 UTC, MasterKale commented on packages/typescript-types/src/index.ts
> +  attestationFormats: string[];
The way I'm reading the spec, these should be marked optional because they're not marked `required` in the spec draft:

https://pr-preview.s3.amazonaws.com/w3c/webauthn/1663/f903606...d671894.html#dictdef-authenticationextensionsdevicepublickeyinputs

2022-09-20 04:19 UTC, MasterKale commented on packages/typescript-types/src/index.ts
> +
Can this get bumped up above `AuthenticationExtensionsClientOutputsFuture`, to be underneath its corresponding `AuthenticationExtensionsDevicePublicKeyOutputs`? It might make it easier to remember to update one when the other gets updated.

2022-09-21 01:27 UTC, MasterKale reviewed
Can you also revert the changes made to **package-lock.json**? I think whatever created those other package-lock.json files you removed also edited the root one, and looking over the changes it looks like some kind of hoisting took place that shouldn't have happened.

Do you have an idea of what might have done this? Can you think of any commands you ran that might be responsible?

2022-09-21 08:50 UTC, agektmr commented
Hmm, no idea. I only run npm scripts.

2022-10-02 06:57 UTC, agektmr commented on packages/typescript-types/src/index.ts
> +  devicePubKey?: AuthenticationExtensionsDevicePublicKeyOutputsJSON
Done.

2022-10-05 06:07 UTC, MasterKale commented on packages/browser/src/helpers/parseClientExtensionResults.ts
> +  }
What about something like this, it's fewer iterations and is a little easier to read IMO:

```suggestion
  const { appid, credProps, devicePubKey, uvm } = clientExtensionResults;

  if (appid) {
    clientExtensionResultsJSON.appid = appid;
  }

  if (credProps) {
    clientExtensionResultsJSON.credProps = credProps;
  }

  if (uvm) {
    clientExtensionResultsJSON.uvm = clientExtensionResults.uvm;
  }

  if (devicePubKey) {
    clientExtensionResultsJSON.devicePubKey = {
      authenticatorOutput: bufferToBase64URLString(devicePubKey.authenticatorOutput),
      signature: bufferToBase64URLString(devicePubKey.signature),
    };
  }
```

2022-10-05 06:56 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +        ' but no client extension data were found');
I actually think this line should drop "client" for "authenticator" since my reading of https://www.w3.org/TR/webauthn-2/#authenticator-data tells me that only authenticator extensions are present in `authenticatorData`.
```suggestion
        ' but no authenticator extension data were found');
```

2022-10-05 06:56 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +      const { authenticatorOutput: encodedAuthenticatorOutput, signature } = devicePubKey;
Why does `authenticatorOutput` get assigned to a different name here? I don't see any other variables by that name in this scope 🤔

2022-10-05 06:56 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +    if (!clientExtensionResults) {
I actually think `!clientExtensionResults` here should be `!extensionsData`, since the `ed` flag in authenticatorData is about the presence of _authenticator_ extension output.

2022-10-05 06:56 UTC, MasterKale commented on packages/server/src/extensions/devicePublicKey/isRecognizedDevice.ts
>            throw new Error('DevicePublicKey attestation could not be verified.');
This `Error` should reveal why the equality check failed:
```suggestion
          const _err = err as Error;
          throw new Error(`DevicePublicKey attestation could not be verified: ${_err.message}`);
```

2022-10-05 06:56 UTC, MasterKale commented on packages/server/src/extensions/devicePublicKey/verifyDevicePublicKeyAttestation.ts
> +    throw new Error('Attestation verification on a device public key is not implemented yet.');
Curious why this might be? Is the attestation statement format not yet decided? I thought it was going to be similar to the attestation statement returned from direct attestation during credential creation.

2022-10-05 06:56 UTC, MasterKale commented on packages/server/src/extensions/devicePublicKey/verifyDevicePublicKeySignature.ts
>    // the `verifySinature` signature, we name it `credentialPublicKey`.
These comments can be deleted since the `credentialPublicKey` they're describing is getting deleted here.

2022-10-05 06:56 UTC, MasterKale commented on packages/server/src/registration/verifyRegistrationResponse.ts
> +        ' but no client extension data were found');
Same thing as in `verifyAuthenticationResponse()`, I'm understanding it to be better to check that `extensionsData` is present since `getClientExtensionResults()` can return different extension results than what the authenticator might include in authenticatorData. Right? Or maybe I've misunderstood `authenticatorData` extensions this whole time.

2022-10-05 07:12 UTC, agektmr commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +      const { authenticatorOutput: encodedAuthenticatorOutput, signature } = devicePubKey;
Good catch. Will fix.

2022-10-05 07:16 UTC, agektmr commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +    if (!clientExtensionResults) {
I wasn't aware that `ed` indicates the presence of authenticator extension output. In that case, we don't need to check both `ed` and `extentionsData` as they are not dealt anyway.

2022-10-05 07:22 UTC, agektmr commented on packages/server/src/extensions/devicePublicKey/verifyDevicePublicKeyAttestation.ts
> +    throw new Error('Attestation verification on a device public key is not implemented yet.');
I'm not familiar with the reasoning for this, but we are not shipping attestation support for dpk at least the initial version.

2022-10-05 07:25 UTC, agektmr commented on packages/server/src/extensions/devicePublicKey/verifyDevicePublicKeySignature.ts
>    // the `verifySinature` signature, we name it `credentialPublicKey`.
What do you mean by "getting deleted"?

2022-10-05 15:45 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +    if (!clientExtensionResults) {
Yeah, I'm looking at a Touch ID response in Chrome and `ed` is false even though I requested the client extension `credProps` and got a response back:

https://debugger.simplewebauthn.dev/?credential=ewogICJpZCI6ICJURW0yaXRRUlh6NEEyZ012bDczSHdQMC1pVWZFZzN6VWpVMzBGdk12UklBIiwKICAicmF3SWQiOiAiVEVtMml0UVJYejRBMmdNdmw3M0h3UDAtaVVmRWczelVqVTMwRnZNdlJJQSIsCiAgInJlc3BvbnNlIjogewogICAgImF0dGVzdGF0aW9uT2JqZWN0IjogIm8yTm1iWFJrYm05dVpXZGhkSFJUZEcxMG9HaGhkWFJvUkdGMFlWaWsyeW00U2lwMWNQVkd1UGp0cDR3Z1dvc0VOTU00R3dJMGhTTzBJc1EyNU9SRkFBQUFBSzNPQUFJMXZNWUtaSXNMSmZId1ZRTUFJRXhKdG9yVUVWOC1BTm9ETDVlOXg4RDlQb2xIeElOODFJMU45QmJ6TDBTQXBRRUNBeVlnQVNGWUlOcjJjeFhPLXZ5b0E4ZjVkcVVuMXkzRXV4dVFvamw0MjZPUjUwUjFCdjdJSWxnZzJaOGVPQTRibFY0ZVJrRUlsMllTcEI5TXl5VkJ4M090M2xmUUJ2aXRNQnciLAogICAgImNsaWVudERhdGFKU09OIjogImV5SjBlWEJsSWpvaWQyVmlZWFYwYUc0dVkzSmxZWFJsSWl3aVkyaGhiR3hsYm1kbElqb2lMVlY2TlhsMmJtTm9ORWt6VlROMGVXbzJSVTVtVFZkc1dsUkJhWE16T1ZKc2NtNUVNRkYwZERsV05DSXNJbTl5YVdkcGJpSTZJbWgwZEhCek9pOHZaWGhoYlhCc1pTNXphVzF3YkdWM1pXSmhkWFJvYmk1a1pYWWlMQ0pqY205emMwOXlhV2RwYmlJNlptRnNjMlY5IgogIH0sCiAgInR5cGUiOiAicHVibGljLWtleSIsCiAgImNsaWVudEV4dGVuc2lvblJlc3VsdHMiOiB7CiAgICAiY3JlZFByb3BzIjogewogICAgICAicmsiOiB0cnVlCiAgICB9CiAgfSwKICAidHJhbnNwb3J0cyI6IFsKICAgICJpbnRlcm5hbCIKICBdCn0

So based on this I'd say `ed` only reflects whether `authenticatorData` contains any extension data.

2022-10-05 15:49 UTC, MasterKale commented on packages/server/src/extensions/devicePublicKey/verifyDevicePublicKeySignature.ts
>    // the `verifySinature` signature, we name it `credentialPublicKey`.
Oh, whoops, I saw all the red and missed that you removed all that to assign `authenticatorOutput.dpk` to `credentialPublicKey`.

2022-10-06 02:38 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> -    }
Note to self: make sure this doesn't end up breaking FIDO Conformance

2022-10-06 02:39 UTC, MasterKale commented on packages/server/src/registration/verifyRegistrationResponse.ts
> -    }
Note to self: make sure the removal of this check doesn't end up breaking FIDO Conformance before merging into master

2022-10-06 02:39 UTC, MasterKale approved these changes

2022-10-06 02:40 UTC, merged

2022-10-06 02:47 UTC, MasterKale commented
This changes have been published as **@simplewebauthn/server@6.3.0-alpha.1** and **@simplewebauthn/browser@6.3.0-alpha.1**