Add origin in authentication and registration info
MasterKale/SimpleWebAuthn pull request #415
Opened 2023-07-19 13:31 UTC by Mikescops

For now I only added the origin to the response.
The rpID is hashed, I'm not sure it is super relevant, what do you think @MasterKale ?

Closes #414

2023-07-20 07:30 UTC, Mikescops commented
@MasterKale thanks for the tip, good to go now 👍

2023-07-20 13:21 UTC, MasterKale requested changes

2023-07-20 13:21 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +    rpId: string;
I'm sure it's driven people nuts that I do this, but in this project the "D" in the camel-cased "RP ID" is always capitalized:

```suggestion
    rpID: string;
```

2023-07-20 13:21 UTC, MasterKale commented on packages/server/src/registration/verifyRegistrationResponse.ts
> +    rpId?: string;
Same thing here, for consistency's sake:

```suggestion
    rpID?: string;
```

2023-07-20 13:32 UTC, Mikescops commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +    rpId: string;
your code is very heterogeneous about this naming, i have checked other interfaces and you use more rpId than rpID

2023-07-20 13:52 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +    rpId: string;
...Shoot, really? Am I at least consistent in the public API of the core methods? 😅 

I'll take a look when I'm on a computer, I thought I was better about using "`rpID`"...

2023-07-20 14:40 UTC, Mikescops commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +    rpId: string;
well I see:

- expectedRPID
- rpIdHash
- matchExpectedRPID
- rpID

but in typescript-types it's `PublicKeyCredentialRequestOptionsJSON.rpId`

let's rename then

2023-07-20 16:13 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.ts
> +    rpId: string;
In the **public** API for @simplewebauthn/server methods I think I've been consistent with casing on inputs so far:

- `generateRegistrationOptions()`: `rpID`
- `verifyRegistrationResponse()`: `expectedRPID`

- `generateAuthenticationOptions()`: `rpID`
- `verifyAuthenticationResponse()`: `expectedRPID`

The point I was attempting to make is that I think it would be weird to have "`rpID`" as an input, and then get "`rpId"` out. But you've already agreed with me and renamed to `rpID` so I suppose this'll serve as something I can point to in the future whenever someone attempts to introduce `rpId` into the library's public API 😛 

> but in typescript-types it's `PublicKeyCredentialRequestOptionsJSON.rpId`

That's why I supposed that I've probably driven people nuts by going with `rpID` in this package while in the WebAuthn spec they use `rpId`. `PublicKeyCredentialRequestOptionsJSON.rpId` maps to the data structure in the L3 Draft of the spec:

https://w3c.github.io/webauthn/#dictdef-publickeycredentialrequestoptionsjson

In typical use of SimpleWebAuthn, pairing **@simplewebauthn/browser** with **@simplewebauthn/server**, the nice thing is that an RP doesn't need to think about things like this!

2023-07-20 21:47 UTC, MasterKale requested changes
Thanks for handling all my comments @Mikescops! Just a couple more around refining tests and then I think this is good to go 🚀

2023-07-20 21:47 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.test.ts
> +  expect(verification.authenticationInfo?.rpID).toEqual('dev.dontneeda.pw');
We don't need to include this `rpID` expectation in this test since this test is specifically about the `origin` that's returned.

Instead I think it would be better for this expectation to go in the 'should support multiple possible RP IDs'` test below.

2023-07-20 21:47 UTC, MasterKale commented on packages/server/src/authentication/verifyAuthenticationResponse.test.ts
> +  expect(verification.authenticationInfo?.rpID).toEqual('dev.dontneeda.pw');
`origin` and `rpID` aren't really relevant in this test since the test ensures we return credential backup info. The test would be fine without these.

2023-07-20 21:47 UTC, MasterKale commented on packages/server/src/registration/verifyRegistrationResponse.test.ts
> +  expect(verification.registrationInfo?.origin).toEqual('https://dev.dontneeda.pw');
I'd leave this `origin` expectation out of this test because the test specifically says it's testing that an `undefined` expected RP ID will return undefined from the method. The origin isn't here nor there (and has sufficient coverage with all of the other tests you've added in here) that we should be fine to remove this from here.

2023-07-20 21:48 UTC, MasterKale commented on packages/server/src/registration/verifyRegistrationResponse.ts
> +    rpID?: string;
Note to future-self: I wish this wasn't optional, but alas...it still drives me nuts that FIDO Conformance made me make `expectedRPID` optional in #25.

2023-07-27 06:56 UTC, Mikescops commented
I think it's mergeable now 👍 cc @MasterKale

2023-07-27 15:42 UTC, merged