chore: use caret specifier for dependencies
MasterKale/SimpleWebAuthn pull request #68
Opened 2020-11-04 15:19 UTC by jstewmon

Using the caret specifier allows package consumers to adopt newer,
compatible versions of transient dependencies, which has the following
benefits:
- de-duplication of compatible package versions
- bug and security fixes can be adopted without waiting on a new version
  of the referencing package

--------

👋  Hi, I found this to be an issue when reinstalling `@simplewebauthn/server` in my project did not pick up the latest version of `@peculiar/asn1-schema` as expected.

2020-11-04 16:58 UTC, MasterKale commented
Dependencies were intentionally pinned (see PR #60) because of a breaking change in one of the `@peculiar/asn1-` libraries that incremented the revision number instead of minor version number. This caused a release to break after publication, which is unacceptable in my book.

I'm inclined to continue pinning dependencies for now because it's the closest I can get to deterministic builds as a package maintainer.

2020-11-04 16:59 UTC, MasterKale commented on .gitignore
> +package-lock.json
Please don't ignore package-lock.json files, building JS apps is difficult enough without these attempting to help ensure the same package version gets used each time 😩

2020-11-04 17:35 UTC, jstewmon commented on .gitignore
> +package-lock.json
> building JS apps

"apps" is the operative word here - `package-lock.json` is intended to lock the dependencies of application, not libraries.

IIUC all of the existing packages provide libraries. Is that correct?

2020-11-04 17:42 UTC, jstewmon commented
> Dependencies were intentionally pinned (see PR #60) because of a breaking change in one of the `@peculiar/asn1-` libraries that incremented the revision number instead of minor version number. This caused a release to break after publication, which is unacceptable in my book.
> 
> I'm inclined to continue pinning dependencies for now because it's the closest I can get to deterministic builds as a package maintainer.

Mistakes do happen from time to time, but pinning all of the dependencies to a specific version is the proverbial baby with the bathwater.

If a package breaks compatibility, it should be reported, because maintainers usually want to resolve that by releasing a new patch that restores compatibility and by releasing the breaking change with a new major semver.

2020-11-04 17:58 UTC, MasterKale commented on .github/workflows/node.js.yml
> +    - run: npm i
`npm ci` is intentionally used within this CI workflow to ensure reliable installation of dependencies. Please see https://docs.npmjs.com/cli/v6/commands/npm-ci

2020-11-04 18:06 UTC, MasterKale commented
> Mistakes do happen from time to time, but pinning all of the dependencies to a specific version is the proverbial baby with the bathwater.
> 
> If a package breaks compatibility, it should be reported, because maintainers usually want to resolve that by releasing a new patch that restores compatibility and by releasing the breaking change with a new major semver.

The issue, sadly, is one of time and not of willpower. I've tried several times in the past to `npm upgrade` packages that **server** relies on only to encounter functionality that suddenly breaks because of updates to some of the dependencies. I just don't have the time to go through each updated package, figure out why it broke, and then report to each individual package why they broke things to then _hope_ they accept the issue and fix the problem in a timely manner.

If you can, as part of this PR, upgrade all dependencies, pass unit tests, successfully build all libraries, _and_ [verify that FIDO Conformance tests still pass](https://simplewebauthn.dev/docs/advanced/fido-conformance) I'd be more inclined to accept going back to using carets in package versions.

2020-11-04 18:45 UTC, MasterKale commented on .gitignore
> +package-lock.json
Building _anything_ in JS benefits from package-lock.json. If I'm developing and testing against one collection of versioned dependencies, I don't want my build step to pull in a completely different collection, right?

2020-11-05 03:53 UTC, jstewmon commented on .gitignore
> +package-lock.json
> I don't want my build step to pull in a completely different collection, right?

Not necessarily... Unless you [shrinkwrap] your dependencies (strongly discouraged for libraries), users of your package will not get the same dependency versions as you have specified in your lock file (if you use exact version specifiers, they will probably get the same version of your direct dependencies).

Excluding a lock file form library package repositories is a ubiquitous practice. I found a decent post that describes the context around it: https://www.twilio.com/blog/lockfiles-nodejs

I think the end of the _How Publishing a Module Works_ section makes the most succinct point:

> This might cause the "works on my machine" effect by accident since your CI and developer environment might pick up a different version of dependencies than your users.

Consider that the version of one of your dependencies has a bug which is reproducible via your library, leading to an unexpected result for your package user. When the bug is fixed, your library users will have to wait for you to release a new version referencing the new dependency version.

This is a common occurrence with so many transient dependencies.

[shrinkwrap]: https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json

2020-11-05 15:49 UTC, jstewmon commented
> If you can, as part of this PR, upgrade all dependencies, pass unit tests, successfully build all libraries, and verify that FIDO Conformance tests still pass I'd be more inclined to accept going back to using carets in package versions.

👌 I've requested the FIDO Conformance tool. The instructions look straightforward, so I hope to be able to complete the conformance test tomorrow or Monday, time permitting.

> upgrade all dependencies

I'll see how this looks - the only outdated production dependency seems to be `jsrsasign` in the server package.

If any changes are required for any dependencies, I'll stage those on discrete commits, and if there are any significant changes, separate PRs may work better for review.

2020-11-05 17:12 UTC, MasterKale commented
Just a heads up, the conformance tools [finished a big update a day or two ago](https://github.com/fido-alliance/conformance-test-tools-resources/issues/578) - grab the latest v1.5.2 from here when you get your login:

https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.5.2/

2020-11-09 23:45 UTC, jstewmon commented
👋 Hi, just checking in - I've gained access to the conformance test tools, and hope to have results in a day or two, time permitting.

2020-11-16 18:52 UTC, jstewmon commented
👋 I finally got around to running the conformance tests this morning - there were two breaking changes in upstream libraries (cbor and jsrsasign), for which I have included fixes on discrete commits.

The cbor change was a bit awkward to handle - I wasn't sure how you'd like to deal with it, so I took a stab at it. The other alternative I considered was using using `decodeAllSync` and destructuring the first item in the result, but that seemed wasteful, especially in `parseAuthenticatorData` when the method is called multiple times.

I also made a few changes to the example project to ease some friction I experienced setting up the test.

I arranged all of the changes on discrete commits, and each commit should build and pass both the unit and conformance tests, so we can review them all here or move to separate PRs if you prefer.

2020-11-17 05:28 UTC, MasterKale commented
@jstewmon Thank you for putting in the work in tracking down those issues with the latest jsrsasign and node-cbor, that was above and byeond.

This is looking pretty good - I'm optimistic that the project can go back to using carets for package versions. I have a few notes of things you've left but I won't have time to properly leave them for a day or two.

For now, though, since you offered can you please back out your changes to the example project? After today's WACG meeting I took a few minutes to convert the example project entirely over to TypeScript (see PR #71). This is why there are now conflicts in the **example/** directory.

I took inspiration from your idea to use an env var to enable the conformance testing routes so that made it in, though I used `ENABLE_CONFORMANCE` instead - same effect, slightly more readable imo.

And I still want to make sure **selfsigned** works fine with arbitrary domains other than `localhost`. I have a dev domain I point to an intranet address that I use to enable testing on mobile devices while the service is hosted on my laptop. So long as that workflow is preserved then selfsigned looks like a great addition.

2020-11-17 15:54 UTC, jstewmon commented
> For now, though, since you offered can you please back out your changes to the example project? After today's WACG meeting I took a few minutes to convert the example project entirely over to TypeScript (see PR #71) so that I can eventually get the example server automatically deployed somewhere as a demo instance. The move to TypeScript, unfortunately, caused the new conflicts in the **example/** directory...
> 
> And I still want to make sure **selfsigned** works fine with arbitrary domains other than `localhost`. I have a dev domain I point to an intranet address that I use to enable testing on mobile devices while the service is hosted on my laptop. So long as that workflow is preserved then selfsigned looks like a great addition.

No problem. I moved those commits to another [branch](https://github.com/MasterKale/SimpleWebAuthn/compare/master...jstewmon:example-server-commits), so we can pull them in later if desired.

I think the difference you might see with `selfsigned` vs `mkcert` is that the latter gives you the option to install its root ca in your host's trust store, so that you won't see insecure connection warnings. If that's an issue, we could make the server conditionally use `selfsigned` if the files are missing, or we can just update the README with the command needed to provide the files with `mkcert`: `mkcert -key-file localhost.key -cert-file localhost.crt localhost`

2020-11-18 17:10 UTC, jstewmon commented
Hmm... The Netlify checks still failed on this one

2020-11-18 20:11 UTC, MasterKale commented
Huh, this is bizarre, something to do with TypeDoc:

```
9:02:08 AM: Loaded plugin /opt/build/repo/typedoc-plugin-external-module-name
9:02:08 AM: Using TypeScript 3.9.7 from /opt/build/repo/node_modules/typescript/lib
9:02:15 AM: Warning: Missing converter for node with kind MappedType
9:02:15 AM: Warning: Missing converter for node with kind MappedType
9:02:15 AM: Warning: Missing converter for node with kind MappedType
9:02:15 AM: Warning: Missing converter for node with kind MappedType
9:02:16 AM: Warning: Missing converter for node with kind MappedType
9:02:16 AM: Warning: Missing converter for node with kind MappedType
9:02:16 AM: Warning: Missing converter for node with kind MappedType
9:02:16 AM: Warning: Missing converter for node with kind MappedType
9:02:17 AM: /opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19
9:02:17 AM:       throw new _exception2['default']('Missing helper: "' + arguments[arguments.length - 1].name + '"');
9:02:17 AM:       ^
9:02:17 AM: Error: Missing helper: "stringify"
9:02:17 AM:     at Object.<anonymous> (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
9:02:17 AM:     at Object.wrapper (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
9:02:17 AM:     at eval (eval at createFunctionContext (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:9:151)
9:02:17 AM:     at prog (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
9:02:17 AM:     at Object.invokePartial (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/runtime.js:334:12)
9:02:17 AM:     at Object.invokePartialWrapper [as invokePartial] (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/runtime.js:84:39)
9:02:17 AM:     at eval (eval at createFunctionContext (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:9:28)
9:02:17 AM:     at Object.prog [as fn] (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
9:02:17 AM:     at Object.<anonymous> (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:29:22)
9:02:17 AM:     at Object.wrapper (/opt/build/repo/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19) {
9:02:17 AM:   description: undefined,
9:02:17 AM:   fileName: undefined,
9:02:17 AM:   lineNumber: undefined,
9:02:17 AM:   endLineNumber: undefined,
9:02:17 AM:   number: undefined
9:02:17 AM: }
9:02:17 AM: npm ERR! code ELIFECYCLE
9:02:17 AM: npm ERR! errno 1
9:02:17 AM: npm ERR! simplewebauthn-monorepo@ docs: `npm run bootstrap && typedoc --tsconfig tsconfigdoc.json`
9:02:17 AM: npm ERR! Exit status 1
9:02:17 AM: npm ERR!
9:02:17 AM: npm ERR! Failed at the simplewebauthn-monorepo@ docs script.
9:02:17 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
9:02:17 AM: npm ERR! A complete log of this run can be found in:
9:02:17 AM: npm ERR!     /opt/buildhome/.npm/_logs/2020-11-18T17_02_17_875Z-debug.log
```

2020-11-18 22:22 UTC, jstewmon commented
Hm... it works for me locally:
```
Using TypeScript 3.9.7 from /Users/jstewmon/dev/public/SimpleWebAuthn/node_modules/typescript/lib
Warning: Missing converter for node with kind MappedType
Warning: Missing converter for node with kind MappedType
Warning: Missing converter for node with kind MappedType
Warning: Missing converter for node with kind MappedType
Warning: Missing converter for node with kind MappedType
Warning: Missing converter for node with kind MappedType
Warning: Missing converter for node with kind MappedType
Warning: Missing converter for node with kind MappedType
Rendering [========================================] 100%

Documentation generated at /Users/jstewmon/dev/public/SimpleWebAuthn/docs
```

As a shot in the dark, I added a new commit to bumping the caret version to the latest beta to see if maybe CI was failing with an older version from cache.

2020-11-18 22:23 UTC, jstewmon commented
🤔 looks like my hunch may have been right - all checks passed 🎉

2020-11-18 23:55 UTC, MasterKale requested changes
Thank you for all the hard work on this PR, after taking another look over it I'm this close to approving this for merge. Can you take a look at my Github workflow comment, and I want to take a look at that Twilio article you posted to get more comfortable with the idea of abandoning package-lock.json files in this PR.

2020-11-18 23:55 UTC, MasterKale commented on .github/workflows/node.js.yml
> +    - run: npm i
@jstewmon Can you revert this change? I still think this should use `npm ci`, unless this is some other aspect of library authoring that I'm ignorant of (which is very possible, I still need to re-read that article you posted about package-lock.json)

2020-11-19 00:08 UTC, MasterKale commented on .github/workflows/node.js.yml
> +    - run: npm i
Nevermind, I finally read that Twilio article and understand that `npm ci` installs what's in package-lock.json. Since they're getting left out of this project that just leaves `npm i` instead.

2020-11-19 00:16 UTC, MasterKale approved these changes
I'm (finally) giving this a stamp of approval, thank you again for all of your time and patience. 

@jstewmon After looking at your series of PR's I think I'd like to merge this one first, then re-evaluate #67. I'm in a much better place time-wise to review that PR and understand its improvements to the code base because there are lessons in there too for me.

2020-11-19 02:54 UTC, jstewmon commented
@MasterKale Sounds good - thanks for churning through this with me  🙏

I really should have said this earlier, but thank you for creating & maintaining this project - the code is very well organized and the API is very easy to use. 💯

2020-11-19 14:45 UTC, merged