Optional Allow Credential
MasterKale/SimpleWebAuthn pull request #79
Opened 2020-12-04 14:02 UTC by Moumouls

2020-12-04 14:12 UTC, Moumouls commented
@MasterKale not sure about what happening into the CI, `npm test` is okay on my side, TS is also ok on the file. Do you have an idea ?

2020-12-04 16:10 UTC, MasterKale commented
@Moumouls I looked at Actions output and TypeScript is complaining that the `PublicKeyCredentialRequestOptionsJSON` type in the **typescript-types** package wasn't updated to allow `allowCredentials` to be optional. I don't know why it's compiling on your end but it's a legitimate issue with this PR.

I'll review the rest of the PR later today.

2020-12-04 20:21 UTC, Moumouls commented
@MasterKale okay i understand the issue, since i'm not sure to understand the typescript types package, is there any way to add the typecheck of this package via `npm test`. Currently error is only raised after a full `bootstrap` command.

2020-12-07 05:21 UTC, MasterKale requested changes

2020-12-07 05:21 UTC, MasterKale commented on packages/browser/src/methods/startAssertion.test.ts
> +  const checkWithOpts = async (opts: PublicKeyCredentialRequestOptionsJSON) => {
Can you please create a new unit test for "should support optional allowCredentials" instead of expanding this existing one?

2020-12-07 05:21 UTC, MasterKale commented on packages/browser/src/methods/startAssertion.ts
> +      requestOptionsJSON.allowCredentials?.length === 0
I'm not a huge fan of ternaries - can you please move this logic to a separate `if ()` statement below this definition of `publicKey`?

2020-12-07 05:25 UTC, MasterKale commented on README.md
> +Dev on the server package with jest watch target
This addition to the README may not be needed since the Jest watch mode offers much more robust ways of narrowing tests by test name, filename, etc... Can we leave this out for that functionality?

2020-12-07 07:50 UTC, Moumouls commented on README.md
> +Dev on the server package with jest watch target
it was just for DX, the suggested `npx lerna exec npm run test:watch --scope=@simplewebauthn/server` i think is a little bit too long. You just want to remove it from the readme ?

2020-12-07 07:50 UTC, Moumouls commented on README.md
> +Dev on the server package with jest watch target
it was just for DX, the suggested npx lerna exec npm run test:watch --scope=@simplewebauthn/server i think is a little bit too long. You just want to remove it from the readme ?

2020-12-07 07:56 UTC, Moumouls commented on packages/browser/src/methods/startAssertion.ts
> +      requestOptionsJSON.allowCredentials?.length === 0
May be te ternary is inverted and should finish by `undefined`,but i think it's here the good way to achieve the result.
What bothers you with ternary ? :)

2020-12-07 15:39 UTC, MasterKale commented on README.md
> +Dev on the server package with jest watch target
I think the new `dev:server` and `dev:browser` scripts are great, this comment is specifically about removing this addition to the README.

2020-12-07 15:44 UTC, MasterKale requested changes

2020-12-07 15:44 UTC, MasterKale commented on packages/browser/src/methods/startAssertion.test.ts
> +  // Should convert empty array to undefined
This should become a separate unit test too.

2020-12-07 15:44 UTC, MasterKale commented on packages/browser/src/methods/startAssertion.test.ts
> +  await startAssertion(goodOpts3);
`goodOpts3` isn't used anywhere but this test, can you please move its definition into here instead? Same thing with `goodOpts4` when you split that into a new unit test, move its declaration into the unit test so we have fewer "goodOpts" variables (it's a bad pattern I established early on, I'm trying to prevent it from becoming the norm 😅)

2020-12-08 16:26 UTC, MasterKale commented on packages/server/src/assertion/generateAssertionOptions.ts
> + * device can ask user which credential he wants to use
This is a slight docs tweak but can you make it say this instead?

> Authenticators previously registered by the user, if any. If undefined the client will ask the user which credential they want to use

2020-12-08 18:10 UTC, MasterKale approved these changes
This looks great, thanks for including unit tests :v:

2020-12-08 18:11 UTC, merged